# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Lint
        run: chmod +x ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html